 const [ip,setIp] = useState(null)
  const [showChild, setShowChild] = useState(false);

  useEffect(() => {
    setShowChild(true);
  }, []);
  
  useEffect(() => {
    if(showChild){
        let enteredIp = window.prompt("Please enter your pico's IP:");
        if (enteredIp == null || enteredIp == "") {
          alert("Can't proceed without IP Address. Please press ok and reload.");
        } else {
          setIp(enteredIp)
        }
    }
  }, [showChild]);

  if (!showChild) {
    return null;
  }

  if (typeof window === 'undefined') {
    return <></>;
  } else {
    return <>
    <Head>
      <title>IOT Project</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    {
    <main className={styles.main}>
      <div className={styles.container}>
        <h1 className={styles.title}>Smart House Controller</h1>
          {
            ip ?  
            data.map((data,index)=><ControlContainer key={index} name={data.roomName} onLink={`http://${ip}${data.roomLink}on`} offLink={`http://${ip}${data.roomLink}off`} />)
            : <p style={{marginLeft:"6px"}}>Please reload & enter IP Address of Pico to continue using app...</p>
          }
          <ControlContainer name="Gate" onLink=`http://${ip}/gateopen` offLink={null}/>
        </div>
      </main>
    </>
  )
}
